name: Safe 4x Daily Commit

on:
  schedule:
    - cron: '0 */6 * * *'  # 4 times a day
  workflow_dispatch:

jobs:
  safe-daily-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Append timestamp at end of README.md
        run: |
          echo "" >> README.md
          echo "<!-- Last updated on $(date -u '+%Y-%m-%d %H:%M:%S UTC') -->" >> README.md

      - name: Commit and push if changed
        run: |
          git config --global user.name "Gulab Ahmad"
          git config --global user.email "gulabahmad724@users.noreply.github.com"
          git add README.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🔄 chore: update timestamp $(date -u '+%Y-%m-%d %H:%M:%S')"
            git push
          fi